### ISSUE TITLE
HTML mode: Correctly scrapes but throws error on save/publish

### ISSUE THREAD

**Issue by cafterh** [Andful/netlify-cms-widget-create-select#5]
Error thrown: https://github.com/Andful/netlify-cms-widget-create-select/blob/487f39d441052af2683f16f7f4ff3eceac749580/src/Control.tsx#L96

Configuration
```yaml
- label: "Tags"
  name: "tags"
  hint: 'Do not duplicate any tags you would rather add for the whole Story!'
  widget: "create-select"
  mode: html
  url: FOO
  query: "h2.tag-title"
  attribute: "data-tag"
  multiple: true
  required: false
```

When this is used as a field, the html data is properly pulled and scraped into a list in the dropdown, but Save/Publish fails silently with an uncaught promise rejection, the field highlighting red and displaying the error above. Any assistance would be much appreciated. I was very excited to use this widget of yours.
